### ISSUE TITLE
vulcand/oxy needs maintainers

### ISSUE THREAD

**Issue by dustin-decker** [vulcand/oxy#208] opened 2020-11-05 20:30 UTC
vulcand/oxy is a great set of middleware for writing proxies that I've found useful several times. Unfortunately, it seems to get very little maintenance attention at this point, with many aging legitimate issues and pull requests. The project needs more attention to remain healthy. I would like to volunteer to assist.

@sylr @emilevauge

**Comment by ldez** [comment] 2020-11-05 21:16
Hello,

We, at Traefik Labs (@emilevauge, @juliens, me) have already made several requests on the subject but people with administrator rights do not answer anymore.

At Traefik Labs, only Emile Vauge have the right to merge PR, but he doesn't have administrator right, so it's not possible to add new maintainers.

**Comment by emilevauge** [comment] 2020-11-05 21:18
Hey @dustin-decker, 
I agree, `vulcand/oxy` lacks a proper maintainers team.
As @ldez said, I personally do only have some merging permissions on the project, and I can't promote anyone.
Maybe @klizhentas could help on this?
Otherwise, we could, ultimately, consider a fork.

**Comment by klizhentas** [comment] 2020-11-06 00:10
@emilevauge @ldez somehow I missed all the requests. Made you folks writers on the repos

**Comment by ldez** [comment] 2020-11-06 00:51
@klizhentas thank you, could you add us as admin? Because with the writer right we are not able to add new maintainers or add CI tools.

**Comment by ldez** [comment] 2020-11-06 00:54
@klizhentas The simplest way to do that is to create a team with only one repo (oxy), and set us as admin of the team and admin of the repo.

**Comment by ldez** [comment] 2020-11-06 01:08
@klizhentas I just saw that you have already created teams, but unfortunately without the `admin` or `maintain` rights on the repo we would not be able to add CIs, and without the `admin` rights on the team would not be able to promote new maintainers.

**Comment by sshahcodes** [comment] 2020-11-25 14:25
Hi,
We use oxy for our project (https://github.com/seknox/trasa), especially as a forwarder for identity-aware access proxy. 
I would love to participate as a maintainer.

**Comment by ldez** [comment] 2021-09-09 18:04
@klizhentas can you add the `admin` or `maintains` rights on the repo to the team [traefik](https://github.com/orgs/vulcand/teams/traefik) or [open-source-contributors](https://github.com/orgs/vulcand/teams/open-source-contributors)?
Currently, the CI is broken then we cannot merge any PR.  
Thank you.

**Comment by ldez** [comment] 2021-10-16 20:11
ping @klizhentas

**Comment by ldez** [comment] 2021-12-21 11:38
ping @klizhentas

**Comment by ldez** [comment] 2022-01-14 18:04
ping @klizhentas :pray:

**Comment by thrawn01** [comment] 2022-05-04 19:49
@ldez I've granted @vulcand/traefik and @vulcand/open-source-contributors `maintains` rights for this repo.

**Comment by ldez** [comment] 2022-05-04 19:51
@thrawn01 can you also add the `maintainer` rights on the team(s) to be able to promote new maintainers?

**Comment by ldez** [comment] 2022-05-04 19:57
@thrawn01 sorry but I need `admin` rights on the repo to be able to fix the CI.

**Comment by thrawn01** [comment] 2022-05-04 20:03
Can you join Gopher slack, so we can continue to collaborate on this? I don't have permissions to promote team members to `maintainer`. We might need to re-create those teams without @klizhentas as the owner of the team.

**Comment by ldez** [comment] 2022-05-04 20:27
So the problem is now fixed!! Thank you @thrawn01 :heart:

**Closed by ldez** 2022-05-04 20:27 UTC
